PROCESS BEFORE OUTPUT.

MODULE %_INIT_PBO.

MODULE %_PBO_REPORT.

MODULE %_PF_STATUS.

MODULE %_END_OF_PBO.

PROCESS AFTER INPUT.

  MODULE %_BACK AT EXIT-COMMAND.

  MODULE %_INIT_PAI.

CHAIN.
  FIELD TESTRUN .
  FIELD UPDATE  .
  FIELD GENVIEW .
  FIELD SHOWLOGS.
    MODULE %_RADIOBUTTON_GROUP_EXEC                          .
ENDCHAIN.

FIELD !SE54IA MODULE %_SE54IA .

FIELD !SE54IM MODULE %_SE54IM .

CHAIN.
  FIELD TESTRUN .
  FIELD UPDATE  .
  FIELD GENVIEW .
  FIELD SHOWLOGS.
  FIELD SE54IA .
  FIELD SE54IM .
  MODULE %_END_OF_SCREEN.
  MODULE %_OK_CODE_1000.
ENDCHAIN.