private section.

  data MT_APP_COMPONENT type /SDF/CL_RC_CHK_UTILITY=>TY_SMDB_APP_COMP_TAB .
  data MT_CHECK type /SDF/CL_RC_CHK_UTILITY=>TY_SMDB_CHECK_TAB .
  data MT_CHECK_RESULT type /SDF/CL_RC_CHK_UTILITY=>TY_CHECK_RESULT_TAB .
  data MT_CONV_TARGET_STACK type /SDF/CL_RC_CHK_UTILITY=>TY_CONV_TARGET_STACK_TAB .
  data MT_CVERS type /SDF/CL_RC_CHK_UTILITY=>TY_CVERS_TAB .
  data MT_NOTE type /SDF/CL_RC_CHK_UTILITY=>TY_SMDB_NOTE_TAB .
  data MT_PPMS_PRODUCT type /SDF/CL_RC_CHK_UTILITY=>TY_PPMS_PRODUCT_TAB .
  data MT_PPMS_PROD_VERSION type /SDF/CL_RC_CHK_UTILITY=>TY_PPMS_PROD_VERSION_TAB .
  data MT_PPMS_STACK type /SDF/CL_RC_CHK_UTILITY=>TY_PPMS_STACK_TAB .
  data MT_SITEM type /SDF/CL_RC_CHK_UTILITY=>TY_SMDB_ITEM_TAB .
  data MT_SOURCE_RELEASE type /SDF/CL_RC_CHK_UTILITY=>TY_SMDB_SOURCE_TAB .
  data MT_TARGET_RELEASE type /SDF/CL_RC_CHK_UTILITY=>TY_SMDB_TARGET_TAB .
  data MV_TARGET_PROD_VER type /SDF/CL_RC_CHK_UTILITY=>TY_BORMNR .
  data MV_TARGET_STACK type /SDF/CL_RC_CHK_UTILITY=>TY_BORMNR .
  data MV_PROD_VER_NUMBER_MIN type /SDF/CL_RC_CHK_UTILITY=>TY_BORMNR value '73555000100900001788' ##NO_TEXT.
  data MV_PROD_VER_NUMBER_MIN_S4 type /SDF/CL_RC_CHK_UTILITY=>TY_BORMNR value '73555000100900001152' ##NO_TEXT.

  methods CHECK_APPLICABILITY .
  methods CHECK_APPLICABLE_SOURCE_RELEAS
    importing
      !IV_SITEM_GUID type GUID_32
    returning
      value(RV_SOURCE_MATCH) type FLAG .
  methods CHECK_APPLICABLE_TARGET_RELEAS
    importing
      !IV_SITEM_GUID type GUID_32
    exporting
      !EV_TARGET_MATCH type FLAG
      !ES_MATCH_TARGET_REL type /SDF/CL_RC_CHK_UTILITY=>TY_SMDB_TARGET_STR .
  methods ADD_CONSIS_RESULT_TO_REL_CHK
    importing
      !IS_HEADER_INFO type /SDF/CL_RC_CHK_UTILITY=>TY_RELEV_CHK_HEADER_STR optional .
  methods CHECK_RELEVANCE .
  methods GET_BUZ_IMPACT_NOTE .
  methods CONSTRUCTOR
    importing
      !IV_TARGET_STACK type /SDF/CL_RC_CHK_UTILITY=>TY_BORMNR optional
    exceptions
      ERROR .