*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
INCLUDE /SDF/LGEN_FUNCSV13 .

FUNCTION $$UNIT$$ /SDF/GEN_FUNCS_S4_SICMETA

    IMPORTING
       VALUE(IV_URL) TYPE !STRING
    EXPORTING
       VALUE(EV_CONTENT) TYPE !XSTRING
       VALUE(EV_MSG) TYPE !STRING.