*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
FUNCTION $$UNIT$$ /SDF/GEN_FUNCS_S4_CONS_EXIT

    IMPORTING
       VALUE(IV_TARGET_STACK) TYPE !/SDF/CL_RC_CHK_UTILITY=>TY_BORMNR
       VALUE(IV_SITEM_GUID) TYPE !GUID_32
       VALUE(IV_SITEM_ID) TYPE !STRING
    EXPORTING
       REFERENCE(ET_CHK_RESULT) TYPE
 !/SDF/CL_RC_CHK_UTILITY=>TY_PRE_CONS_CHK_RESULT_TAB.