*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
FUNCTION $$UNIT$$ /SDF/GEN_FUNCS_S4_READ_STAKXML

    EXPORTING
       REFERENCE(EV_TARGET_STACK) TYPE !BORM_ID.