*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY               **
*   NEVER CHANGE IT MANUALLY, PLEASE!                            **
*******************************************************************
FORM /SDF/GEN_FUNCS_S4_TARG_STK_GET %_RFC.
* Parameter declaration
DATA EV_ERR_MESG TYPE
STRING
.
DATA EV_RESULT_XSTR TYPE
XSTRING
.
DATA EV_BW_RESULT_XSTR TYPE
XSTRING
.
* Assign default values
* Call remote function
  CALL FUNCTION '/SDF/GEN_FUNCS_S4_TARG_STK_GET' %_RFC
     IMPORTING
       EV_ERR_MESG = EV_ERR_MESG
       EV_RESULT_XSTR = EV_RESULT_XSTR
       EV_BW_RESULT_XSTR = EV_BW_RESULT_XSTR
  .
ENDFORM.