*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
INCLUDE /SDF/LGEN_FUNCSV08 .
FUNCTION $$UNIT$$ /SDF/GEN_FUNCS_S4_TARG_STK_GET

    EXPORTING
       VALUE(EV_ERR_MESG) TYPE !STRING
       VALUE(EV_RESULT_XSTR) TYPE !XSTRING
       VALUE(EV_BW_RESULT_XSTR) TYPE !XSTRING .