*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY               **
*   NEVER CHANGE IT MANUALLY, PLEASE!                            **
*******************************************************************
FORM /SDF/GEN_FUNCS_S4_SICMETA %_RFC.
* Parameter declaration
DATA IV_URL TYPE
STRING
.
DATA EV_CONTENT TYPE
XSTRING
.
DATA EV_MSG TYPE
STRING
.
* Assign default values
* Call remote function
  CALL FUNCTION '/SDF/GEN_FUNCS_S4_SICMETA' %_RFC
     EXPORTING
       IV_URL = IV_URL
     IMPORTING
       EV_CONTENT = EV_CONTENT
       EV_MSG = EV_MSG
  .
ENDFORM.