*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
INCLUDE /SDF/LGEN_FUNCSV10 .

FUNCTION $$UNIT$$ /SDF/GEN_FUNCS_S4_REL_CHK_JOB

    IMPORTING
       VALUE(IV_TARGET_STACK) TYPE !CHAR20
       VALUE(IV_NO_CONS_CHECK) TYPE !FLAG OPTIONAL.