*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE /SDF/LGEN_FUNCSU01.
                    "/SDF/GEN_FUNCS_EXT_CALL
INCLUDE /SDF/LGEN_FUNCSU02.
                    "/SDF/GEN_FUNCS_IF_CHECK
INCLUDE /SDF/LGEN_FUNCSU04.
                    "/SDF/GEN_FUNCS_FUNC_CALL
INCLUDE /SDF/LGEN_FUNCSU03.
                    "/SDF/GEN_FUNCS_CALL_DOCU
INCLUDE /SDF/LGEN_FUNCSU06.
                    "/SDF/GEN_FUNCS_S4_CONS_CHK_MAS
INCLUDE /SDF/LGEN_FUNCSU05.
                    "/SDF/GEN_FUNCS_S4_CONS_CHK_SIG
INCLUDE /SDF/LGEN_FUNCSU12.
                    "/SDF/GEN_FUNCS_S4_CONS_EXIT
INCLUDE /SDF/LGEN_FUNCSU09.
                    "/SDF/GEN_FUNCS_S4_DY_SQL_BUILD
INCLUDE /SDF/LGEN_FUNCSU11.
                    "/SDF/GEN_FUNCS_S4_READ_STAKXML
INCLUDE /SDF/LGEN_FUNCSU07.
                    "/SDF/GEN_FUNCS_S4_RELEVAN_CHK
INCLUDE /SDF/LGEN_FUNCSU10.
                    "/SDF/GEN_FUNCS_S4_REL_CHK_JOB
INCLUDE /SDF/LGEN_FUNCSU08.
                    "/SDF/GEN_FUNCS_S4_TARG_STK_GET
INCLUDE /SDF/LGEN_FUNCSU13.
                    "/SDF/GEN_FUNCS_S4_SICMETA