PROCESS BEFORE OUTPUT.

MODULE %_INIT_PBO.

MODULE %_PBO_REPORT.

MODULE %_PF_STATUS.

MODULE %_END_OF_PBO.

PROCESS AFTER INPUT.

  MODULE %_BACK AT EXIT-COMMAND.

  MODULE %_INIT_PAI.

FIELD !P_DEST MODULE %_P_DEST .

FIELD !P_DESC MODULE %_P_DESC .

FIELD !P_HOST MODULE %_P_HOST .

FIELD !P_SYSNR MODULE %_P_SYSNR .


CHAIN.
  FIELD P_HOST .
  FIELD P_SYSNR .
    MODULE %_BLOCK_1000003.
ENDCHAIN.


CHAIN.
  FIELD P_DEST .
  FIELD P_DESC .
  FIELD P_HOST .
  FIELD P_SYSNR .
    MODULE %_BLOCK_1000000.
ENDCHAIN.

FIELD !P_CUSAL MODULE %_P_CUSAL .


CHAIN.
  FIELD P_CUSAL .
    MODULE %_BLOCK_1000008.
ENDCHAIN.

FIELD !P_MAPAL MODULE %_P_MAPAL .

FIELD !P_MAPRFC MODULE %_P_MAPRFC .

FIELD !P_MAPCL MODULE %_P_MAPCL .


CHAIN.
  FIELD P_MAPAL .
  FIELD P_MAPRFC .
  FIELD P_MAPCL .
    MODULE %_BLOCK_1000011.
ENDCHAIN.

CHAIN.
  FIELD P_DEST .
  FIELD P_DESC .
  FIELD P_HOST .
  FIELD P_SYSNR .
  FIELD P_CUSAL .
  FIELD P_MAPAL .
  FIELD P_MAPRFC .
  FIELD P_MAPCL .
  MODULE %_END_OF_SCREEN.
  MODULE %_OK_CODE_1000.
ENDCHAIN.