PROCESS BEFORE OUTPUT.

MODULE %_INIT_PBO.

MODULE %_PBO_REPORT.

MODULE %_PF_STATUS.

MODULE %_SO_BUKRS.

MODULE %_SO_ANLN1.

MODULE %_SO_GJAHR.

MODULE %_END_OF_PBO.

PROCESS AFTER INPUT.

  MODULE %_BACK AT EXIT-COMMAND.

  MODULE %_INIT_PAI.

FIELD !P_CLIENT MODULE %_P_CLIENT .

CHAIN.
  FIELD  SO_BUKRS-LOW.
  FIELD  SO_BUKRS-HIGH.
  MODULE %_SO_BUKRS.
ENDCHAIN.

CHAIN.
  FIELD  SO_ANLN1-LOW.
  FIELD  SO_ANLN1-HIGH.
  MODULE %_SO_ANLN1.
ENDCHAIN.

CHAIN.
  FIELD  SO_GJAHR-LOW.
  FIELD  SO_GJAHR-HIGH.
  MODULE %_SO_GJAHR.
ENDCHAIN.


CHAIN.
  FIELD P_CLIENT .
  FIELD  SO_BUKRS-LOW.
  FIELD  SO_BUKRS-HIGH.
  FIELD  SO_ANLN1-LOW.
  FIELD  SO_ANLN1-HIGH.
  FIELD  SO_GJAHR-LOW.
  FIELD  SO_GJAHR-HIGH.
    MODULE %_BLOCK_1000000.
ENDCHAIN.

FIELD !P_TEST MODULE %_P_TEST .


CHAIN.
  FIELD P_TEST .
    MODULE %_BLOCK_1000008.
ENDCHAIN.

CHAIN.
  FIELD P_CLIENT .
  FIELD  SO_BUKRS-LOW.
  FIELD  SO_BUKRS-HIGH.
  FIELD  SO_ANLN1-LOW.
  FIELD  SO_ANLN1-HIGH.
  FIELD  SO_GJAHR-LOW.
  FIELD  SO_GJAHR-HIGH.
  FIELD P_TEST .
  MODULE %_END_OF_SCREEN.
  MODULE %_OK_CODE_1000.
ENDCHAIN.